version: '3.9'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: univesp
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - ./db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  app_network:
    driver: bridge