version: '3.9'

services:
  db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: univesp
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - ./db_data:/var/lib/mysql

  app:
    build: .
    volumes:
      - .:/app
      - /app/static
      - /app/media
    expose:
      - "9000"
    networks:
      - app_network
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media      
    ports:
      - "9000:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - app_network
      
volumes:
  db_data:

networks:
  app_network:
    driver: bridge