# Generated by Django 5.0.4 on 2024-04-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faltas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DadosExcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("documento", models.CharField(max_length=20)),
                ("data", models.DateField()),
                ("faltas", models.IntegerField()),
                ("processado_recentemente", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="menssagem",
            name="faltas_aluno",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="menssagem",
            name="msg_data",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
