# Generated by Django 5.0.4 on 2024-04-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faltas", "0003_remove_dadosexcel_processado_recentemente"),
    ]

    operations = [
        migrations.AddField(
            model_name="dadosexcel",
            name="fone_aluno",
            field=models.CharField(default=0, max_length=11),
        ),
        migrations.AddField(
            model_name="dadosexcel",
            name="resp_aluno",
            field=models.CharField(default="", max_length=200),
        ),
    ]
