# Generated by Django 5.0.4 on 2024-05-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faltas', '0004_dadosexcel_fone_aluno_dadosexcel_resp_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosexcel',
            name='mensagem_falta',
            field=models.TextField(default=''),
        ),
    ]
