# Generated by Django 5.0.4 on 2024-09-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faltas', '0006_delete_dadosexcel_menssagem_falta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='menssagem',
            name='msg_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
